std = "lua51"
max_line_length = 120

globals = {
	"C_NamePlate",
	"ColorPickerFrame",
	"CreateFrame",
	"GameTooltip",
	"GetNumGroupMembers",
	"GetNumSubgroupMembers",
	"GetNumTalentTabs",
	"GetPartyAssignment",
	"GetShapeshiftForm",
	"GetShapeshiftFormInfo",
	"GetTalentTabInfo",
	"GetTime",
	"IsInGroup",
	"IsInRaid",
	"PlayerUtil",
	"SlashCmdList",
	"SLASH_THREATPLATING1",
	"Settings",
	"ThreatPlatingDB",
	"ThreatPlating_OnAddonCompartmentClick",
	"UIParent",
	"UISpecialFrames",
	"UnitDetailedThreatSituation",
	"UnitExists",
	"UnitGroupRolesAssigned",
	"UnitIsPlayer",
	"UnitIsUnit",
	"UnitPlayerControlled",
	"UnitCanAttack",
	"UnitClass",
	"wipe",
}
